-- ZKTeco Physical Attendance Table
-- Store logs pushed from machines like serial TFEE255000216

CREATE TABLE IF NOT EXISTS public.physical_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_sn TEXT NOT NULL,
    zk_user_id TEXT NOT NULL,
    check_time TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    verify_type INTEGER, -- 1: Fingerprint, 2: Face, 3: Card, 4: Password
    status INTEGER,     -- 0: Check-In, 1: Check-Out, 4: Overtime-In, 5: Overtime-Out
    raw_payload TEXT,    -- For debugging raw ADMS data
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fast lookup by User ID (ZKTeco)
CREATE INDEX IF NOT EXISTS attendance_zk_user_idx ON public.physical_attendance (zk_user_id);
CREATE INDEX IF NOT EXISTS attendance_time_idx ON public.physical_attendance (check_time DESC);

-- Enable RLS
ALTER TABLE public.physical_attendance ENABLE ROW LEVEL SECURITY;

-- Policies: Only Admins can view
DROP POLICY IF EXISTS "Admins can view attendance" ON public.physical_attendance;
CREATE POLICY "Admins can view attendance" 
ON public.physical_attendance FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND role = 1
  )
);
