-- User Visit Tracking Table
CREATE TABLE IF NOT EXISTS public.user_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    visited_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Optimization: Index for daily stats
CREATE INDEX IF NOT EXISTS user_visits_visited_at_idx ON public.user_visits (visited_at);

-- Enable RLS
ALTER TABLE public.user_visits ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Users can insert their own visits" ON public.user_visits;
CREATE POLICY "Users can insert their own visits" 
ON public.user_visits FOR INSERT 
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can view all visits" ON public.user_visits;
CREATE POLICY "Admins can view all visits" 
ON public.user_visits FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND role = 1
  )
);
